version: '3'
services:
  mongodb:
    image: "mongo:latest"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=example"
    ports:
      - "27017:27017"
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
  mock-trader:
    build:
      dockerfile: Dockerfile
      context: ../mock-trader
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      - "rabbitmq"
      - "mongodb"
    links: 
      - rabbitmq
      - mongodb
  robotrade-api:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=example"
    depends_on:
      - "rabbitmq"
      - "mongodb"
    links: 
      - rabbitmq
      - mongodb